import { Geist, Geist_Mono } from "next/font/google";
import {
    arizonia,
    audioWide,
    caveat,
    coiny,
    comic,
    courgette,
    kottaOne,
    lime,
    openSans,
} from "./fonts";
import "./_styles/globals.css";
import { ThemeProvider } from "./_components/ThemeProvider";
import Header from "./_components/Header";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html
            lang="en"
            suppressHydrationWarning
            className={`text-[50%] sm:text-[57.5] md:text-[64.5%] ${geistSans.variable} ${geistMono.variable} ${lime.variable} ${comic.variable} ${caveat.variable} ${coiny.variable} ${openSans.variable} ${arizonia.variable} ${audioWide.variable} ${courgette.variable} ${kottaOne.variable} ${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
            <body className="min-h-full flex flex-col">
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                    enableColorScheme={false}>
                    <Header />
                    {children}
                    <Toaster
                        position="top-center"
                        toastOptions={{
                            duration: 3000,
                            style: {
                                background: "#363636",
                                color: "#fff",
                                padding: "8px",
                                borderRadius: "2px",
                            },
                            success: {
                                duration: 3000,
                                icon: "✅",
                                style: {
                                    background: "#22c55e",
                                    color: "#fff",
                                },
                            },
                            error: {
                                duration: 4000,
                                icon: "❌",
                                style: {
                                    background: "#ef4444",
                                    color: "#fff",
                                },
                            },
                            loading: {
                                duration: Infinity,
                                style: {
                                    background: "#3b82f6",
                                    color: "#fff",
                                },
                            },
                        }}
                    />
                </ThemeProvider>
            </body>
        </html>
    );
}
