import { Geist, Geist_Mono } from "next/font/google";
import {
    arizonia,
    audioWide,
    caveat,
    coiny,
    comic,
    courgette,
    kottaOne,
    lime,
    openSans,
} from "./fonts";
import "./_styles/globals.css";
import { ThemeProvider } from "./_components/ThemeProvider";
import Header from "./_components/Header";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html
            lang="en"
            suppressHydrationWarning
            className={`text-[50%] sm:text-[57.5] md:text-[64.5%] ${geistSans.variable} ${geistMono.variable} ${lime.variable} ${comic.variable} ${caveat.variable} ${coiny.variable} ${openSans.variable} ${arizonia.variable} ${audioWide.variable} ${courgette.variable} ${kottaOne.variable} ${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
            <body className="min-h-full flex flex-col p-2">
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                    enableColorScheme={false}>
                    <Header />
                    {children}
                </ThemeProvider>

                <Toaster
                    position="top-center"
                    containerStyle={{
                        zIndex: 99999999, // ✅ بالاترین z-index
                    }}
                    toastOptions={{
                        duration: 3000,
                        style: {
                            background: "#363636",
                            color: "#fff",
                            padding: "12px 24px",
                            borderRadius: "8px",
                            fontSize: "1.6rem",
                            zIndex: 99999999,
                            boxShadow: "0 10px 40px rgba(0,0,0,0.3)",
                        },
                        success: {
                            duration: 3000,
                            style: {
                                background: "#e1ffdb",
                                color: "#00a572",
                                border: "1px solid #00f572",
                                fontSize: "1.6rem",
                                padding: "12px 24px",
                                borderRadius: "8px",
                                zIndex: 99999999,
                                boxShadow: "0 10px 40px rgba(0,0,0,0.15)",
                            },
                            iconTheme: {
                                primary: "#00a572",
                                secondary: "#e1ffdb",
                            },
                        },
                        error: {
                            duration: 4000,
                            style: {
                                background: "#ffedeb",
                                color: "#ea2901",
                                border: "1px solid #ea0501",
                                fontSize: "1.6rem",
                                padding: "12px 24px",
                                borderRadius: "8px",
                                zIndex: 99999999,
                                boxShadow: "0 10px 40px rgba(0,0,0,0.15)",
                            },
                            iconTheme: {
                                primary: "#ea2901",
                                secondary: "#ffedeb",
                            },
                        },
                        loading: {
                            duration: Infinity,
                            style: {
                                background: "#95cadb",
                                color: "#1d2951",
                                border: "1px solid #95cafb",
                                padding: "12px 24px",
                                borderRadius: "8px",
                                zIndex: 99999999,
                                boxShadow: "0 10px 40px rgba(0,0,0,0.15)",
                            },
                        },
                    }}
                />
            </body>
        </html>
    );
}
